plotter: # All units in mm
  size:
    width:  280
    height: 215
  origin:
    x: 0
    y: 0
    z: 0
  pen:
    offset: # Subtracted from commanded positions
      x: 0
      y: 0
    plunge: -1
    lift:    2
  speed: # mm/s
    plunge: 100
    travel: 3000
    draw:   1500
  output: "graph.gcode"

graph:
  limits:  # Graph limits, unitless
    xmin:  -6
    xmax:   6
    ymin:  -6
    ymax:   6
    zscale: 2
  size:    # Size of plot, in mm
    width:  100
    height: 100
  density: # Points between min and max, inclusive
    x: 20
    y: 20
  rotation: # Graph rotation, in degrees
    x: 45
    y: 0
    z: 45

